compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: pnp

supportedArchitectures:
  os:
    - linux
    - win32
  cpu:
    - x64

yarnPath: .yarn/releases/yarn-4.16.0.cjs
