name: 'Setup MSVC Developer Command Prompt'
description: 'Sets up a Microsoft Visual C++ tools for command-line usage'
author: TheMrMilchmann
inputs:
  arch:
    description: 'The target architecture'
    required: false
  vs-path:
    description: 'The path to the Visual Studio installation'
    required: false
  sdk:
    description: 'Windows SDK to use'
    required: false
  spectre:
    description: 'Use Visual Studio libraries with Spectre mitigations'
    required: false
  toolset:
    description: 'VC++ compiler toolset version'
    required: false
  uwp:
    description: 'Build for Universal Windows Platform'
    required: false
  export-path-to-vcvarsall:
    description: 'The environment variable to store the path to vcvarsall.bat in'
    required: false
  export-path-to-vs:
    description: 'The environment variable to store the path to the Visual Studio installation in'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: terminal
  color: gray-dark